site_name: OpenBLAS
theme:
  name: material
  logo: logo.svg
  favicon: logo.svg
  palette:
    primary: grey
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 4
nav:
  - index.md
  - install.md
  - user_manual.md
  - extensions.md
  - developers.md
  - build_system.md
  - distributing.md
  - ci.md
  - machine_list.md
  - todo.md
  - ecosystem.md
  - publications.md
  - mailing_list.md
  - donate.md
  - faq.md
