name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs gh-deploy --force --clean --verbose
